export function initIconsHover() { 
  const fontAwesomeClasses = [
  "fas fa-headphones",
  "fas fa-laptop",
  "fas fa-mobile-alt",
  "fas fa-desktop",
  "fas fa-gamepad",
  "fas fa-camera",
  "fas fa-video",
  "fas fa-volume-up",
  "fas fa-heart",
  "fas fa-heart-broken",
  "fas fa-face-grin-squint-tears",
  "fas fa-face-smile",
  "fas fa-face-grin-hearts",
  "fas fa-face-grin-stars",
  "fas fa-face-laugh-squint",
  "fas fa-code",
  "fas fa-terminal",
  "fas fa-plug",
  "fas fa-computer-mouse",
  "fas fa-lock",
  "fas fa-server",
  "fas fa-database",
  "fas fa-link",
  "fas fa-shield-alt",
  "fas fa-rocket",
  "fas fa-bolt",
  "fas fa-sparkles",
  "fas fa-trophy",
  "fas fa-bullseye",
  "fas fa-paint-brush",
  "fas fa-music",
  "fas fa-pizza-slice",
  "fas fa-coffee",
  "fas fa-dice",
  "fas fa-computer-mouse",
  "fas fa-lock",
  "fas fa-server",
  "fas fa-database",
  "fas fa-link",
  "fas fa-shield-alt",
  "fas fa-rocket",
  "fas fa-bolt",
  "fas fa-sparkles",
  "fas fa-trophy",
  "fas fa-bullseye",
  "fas fa-paint-brush",
  "fas fa-music",
  "fas fa-pizza-slice",
  "fas fa-coffee",
  "fas fa-dice",
  "fas fa-headphones",
  "fas fa-laptop",
  "fas fa-mobile-alt",
  "fas fa-desktop",
  "fas fa-gamepad",
  "fas fa-camera",
  "fas fa-video",
  "fas fa-volume-up",
  "fas fa-heart",
  "fas fa-heart-broken",
  "fas fa-face-grin-squint-tears",
  "fas fa-face-smile",
  "fas fa-face-grin-hearts",
  "fas fa-face-grin-stars",
  "fas fa-face-laugh-squint",
  "fas fa-code",
  "fas fa-terminal",
  "fas fa-plug",
  "fas fa-computer-mouse",
  "fas fa-lock",
  "fas fa-server",
  "fas fa-database",
  "fas fa-link",
  "fas fa-shield-alt",
  "fas fa-rocket",
  "fas fa-bolt",
  "fas fa-sparkles",
  "fas fa-trophy",
  "fas fa-bullseye",
  "fas fa-paint-brush",
  "fas fa-music",
  "fas fa-pizza-slice",
  "fas fa-coffee",
  "fas fa-dice",
  "fas fa-computer-mouse",
  "fas fa-lock",
  "fas fa-server",
  "fas fa-database",
  "fas fa-link",
  "fas fa-shield-alt",
  "fas fa-rocket",
  "fas fa-bolt",
  "fas fa-sparkles",
  "fas fa-trophy",
  "fas fa-bullseye",
  "fas fa-paint-brush",
  "fas fa-music",
  "fas fa-pizza-slice",
  "fas fa-coffee",
  "fas fa-dice",
  
]
const container = document.querySelector("#icon-container"); // Make sure you have a container element in your HTML

fontAwesomeClasses.forEach(className => {
  const iconElement = document.createElement("i"); // Create an <i> element
  iconElement.className = `hover:scale-125 hover:text-lime-300  
  hover:drop-shadow-[0_0_5px_#4ade80] 
  hover:drop-shadow-[0_0_10px_#4ade80,0_0_20px_#22c55e,0_0_40px_#16a34a]
  focus:drop-shadow-[0_0_5px_#4ade80]
  active:drop-shadow-[0_0_10px_#4ade80,0_0_20px_#22c55e,0_0_40px_#16a34a]
  focus:text-lime-300
  active:text-lime-300
  hover:bg-transparent ${className}`; // Assign the Font Awesome class
  container.appendChild(iconElement); // Append to the container
});
}


